### PR TITLE
fix compile error (add comma)

### PR DESCRIPTION
**Pull request by 978-9-17-637879-3**
sorrow fills the day as i develop imposter syndrome

### CODE REVIEW

**Comment by Toafu** [comment]
My disappointment lies only with the increasing growth of my inbox

**Review by Toafu — APPROVED** [review]

**Comment by 978-9-17-637879-3** [comment]
> My disappointment lies only with the increasing growth of my inbox

don't worry this is also bugged give me  a second

**Review by Toafu — APPROVED** [review]
WE BALL

**Comment by 978-9-17-637879-3** [comment]
Dear Toafu-hime,

As the light within me falls 🌅 another day departs 🌅 if only I could see the dawn 🌅 beyond the shadows cast 🌅 an empire of doubt, a heart full of clouds 🌥 befall the souls within her 💔 the valley will weep as a mirror of old 🌅 as hope is halfway damned 💔 oh, to see our last day with all these shattered voices raised 🗣 oh say, will you fight? 🥊 to seek the glory days 🏆 we'll fight the lion's way 🦁 then let the rain wash all of our pride away 😇 so if this victory 🏆 is our last odyssey 🚗 then let the power within us decide! 💪 on the backs of giants long deceased 💀 are we still standing 🤚 we measure our worth by all the days we wasted then 😔 all of our time, and all of our might, are fueled by the heartache of winter ❄ oh life as we know it is bitter and cold, but souls burn best with spite 🔥 oh, to see our last day with all these shattered voices raised 🗣 oh say, will you fight? 🥊 to seek the glory days 🏆 we'll fight the lion's way 🦁 then let the rain wash all of our pride away 😇 so if this victory 🏆 is our last odyssey 🚗 then let the power within us decide! 💪 if we have to choose our fate 🤞 it's still our choice to make! 😎 oh, to see our last day with all these shattered voices raised 🗣 oh say, will you fight? 🥊 to seek the glory days 🏆 we'll fight the lion's way 🦁 then let the rain wash all of our pride away 😇 to seek the glory days 🏆 we'll fight the lion's way 🦁 then let the rain wash all of our pride away 😇 so if this victory 🏆 is our last odyssey 🚗 let the power within 💪 ignite where we've been 🔥 let the power within us decide! 💪

- Ethan

**Pull request merged**
